# @package _group_
epochs: 20

report_interval: 10
val_interval: 30
num_val_batches: 16

checkpointing: False

data_loaders:
  train:
    split_key: train_idxs
    batch_size: 64
    num_workers: 8
    transforms:
      - horizontal_flip
      - vertical_flip
  validation:
    split_key: val_idxs
    batch_size: 64
    num_workers: 8